version: '3.8'
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - project

  project:
    build:
      context: .
    ports:
      - 8000:8000
      - 8082:8082
    environment:
      - SERVER_PORT=8082
      - MYSQL_URL=jdbc:mysql://mysqlserver:3306/project
    depends_on:
      - mysqlserver
    networks:
      - mysql-db
    volumes:
      - ./:/app
    command: ./mvnw spring-boot:run -Dspring-boot.run.profiles=mysql -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"

  mysqlserver:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=project
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
    networks:
      - mysql-db

volumes:
  mysql_data:
  mysql_config:

networks:
  mysql-db:
    driver: bridge